[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$catalogPath = Join-Path $repositoryRoot 'CATALOG.md'
$gitDirectory = Join-Path $repositoryRoot '.git'
$excelExtensions = @('.xlsx', '.xlsm', '.xlsb', '.xls')

$workbooks = @(
    Get-ChildItem -LiteralPath $repositoryRoot -Recurse -File |
        Where-Object {
            $excelExtensions -contains $_.Extension.ToLowerInvariant() -and
            -not $_.FullName.StartsWith($gitDirectory, [System.StringComparison]::OrdinalIgnoreCase)
        } |
        Sort-Object FullName
)

function ConvertTo-RepositoryPath {
    param([Parameter(Mandatory = $true)][string]$FullName)

    return $FullName.Substring($repositoryRoot.Length + 1).Replace('\', '/')
}

function ConvertTo-MarkdownTarget {
    param([Parameter(Mandatory = $true)][string]$RepositoryPath)

    $encodedSegments = @(
        $RepositoryPath.Split('/') | ForEach-Object {
            [System.Uri]::EscapeDataString($_)
        }
    )

    return $encodedSegments -join '/'
}

function ConvertTo-MarkdownLabel {
    param([Parameter(Mandatory = $true)][string]$Label)

    return $Label.Replace('[', '\[').Replace(']', '\]')
}

$entries = @(
    foreach ($workbook in $workbooks) {
        $repositoryPath = ConvertTo-RepositoryPath -FullName $workbook.FullName
        $directory = [System.IO.Path]::GetDirectoryName($repositoryPath)

        [pscustomobject]@{
            Directory = if ($directory) { $directory.Replace('\', '/') } else { '' }
            FileName = $workbook.Name
            Target = ConvertTo-MarkdownTarget -RepositoryPath $repositoryPath
        }
    }
)

$lines = New-Object 'System.Collections.Generic.List[string]'
$lines.Add('# Model Catalog')
$lines.Add('')
$lines.Add("This catalog is generated from the $($workbooks.Count) Excel workbooks in the repository. Select a filename to open its GitHub file page and download the workbook for full review in Excel.")
$lines.Add('')

$groups = @(
    $entries |
        Group-Object Directory |
        Sort-Object @{ Expression = { if ($_.Name -eq '') { 0 } else { 1 } } }, Name
)

foreach ($group in $groups) {
    $heading = if ($group.Name -eq '') { 'Root models' } else { $group.Name.Replace('/', ' / ') }
    $lines.Add("## $heading")
    $lines.Add('')

    foreach ($entry in $group.Group | Sort-Object FileName) {
        $label = ConvertTo-MarkdownLabel -Label $entry.FileName
        $lines.Add("- [$label]($($entry.Target))")
    }

    $lines.Add('')
}

$lines.Add('---')
$lines.Add('')
$lines.Add('Generated by `tools/Update-Catalog.ps1`. Do not edit this file by hand.')
$content = ($lines -join [System.Environment]::NewLine) + [System.Environment]::NewLine

if ((Test-Path -LiteralPath $catalogPath) -and ([System.IO.File]::ReadAllText($catalogPath) -ceq $content)) {
    Write-Host "Catalog is already current: $($workbooks.Count) workbooks."
    return
}

[System.IO.File]::WriteAllText(
    $catalogPath,
    $content,
    (New-Object System.Text.UTF8Encoding($false))
)

Write-Host "Updated CATALOG.md with $($workbooks.Count) workbooks."
